name: Build TriCNES

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore packages
        run: nuget restore TriCNES.sln

      - name: Build solution (Release)
        run: msbuild TriCNES.sln /p:Configuration=Release

      - name: Prepare upload folder
        run: |
          mkdir upload
          copy bin\Release\TriCNES.exe upload\TriCNES.exe
          mkdir upload\tas
          mkdir upload\roms
          echo "# this is a placeholder file to force to upload this folder" > upload\tas\README.md
          echo "# this is a placeholder file to force to upload this folder" > upload\roms\README.md

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: TriCNES-Release
          path: |
            upload\tas\README.md
            upload\roms\README.md
            upload\TriCNES.exe
            